# Generated by Django 3.2.7 on 2021-09-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=4)),
                ('embalagens', models.CharField(max_length=4)),
                ('comp', models.IntegerField()),
                ('descricao', models.CharField(max_length=255)),
                ('cpv', models.FloatField()),
            ],
        ),
    ]
