version: "3"
services:
  web:
    build:
      context: .
      args:
        - SECRET_KEY
        - ALLOWED_HOSTS
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    env_file:
      - .env
    #command: "simulador.wsgi:application --timeout 1800"
    command: "python ./manage.py runserver 0.0.0.0:8001"

